gui:
  #authorColors:
  # 'Kerim Berdimyradov': '#5D3FD3'
  # 'berdimyradov': '#5D3FD3'
  #  '*': '#C0C0C0'
  nerdFontsVersion: "3"
  theme:
     selectedLineBgColor:
      # Colors of my choice #5F8575 #355E3B #478778
       - '#355E3B' # set to default to have no background colour0000ff' # set to default to have no background colour
  border: 'rounded'
git:
  branchLogCmd: "git log --graph --color=always --format=format:'%<|(7)%C(#ff69b4)%<|(1)%d%C(reset) %<|(80,trunc)%s %C(#777777)| %h%x09%<(15,trunc)%al %x09%ah' {{branchName}}"
os:
  edit: 'nvim {{filename}}'
