# POWERLEVEL9K_PROMT's config
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_PROMPT_ADD_NEWLINE=false 
POWERLEVEL9K_MODE='awesome-fontconfig'
# Add a space in the first prompt
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX="%f"
# Visual customisation of the second prompt line
local user_symbol="$"
if [[ $(print -P "%#") =~ "#" ]]; then
    user_symbol = "#"
fi
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="%{%B%F{black}%K{yellow}%} $user_symbol%{%b%f%k%F{yellow}%} %{%f%}"
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(dir rbenv vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status root_indicator ram)
POWERLEVEL9K_DISABLE_RPROMPT=true
HYPHEN_INSENSITIVE=true
#POWERLEVEL9K_SHORTEN_DIR_LENGTH=7
#POWERLEVEL9K_SHORTEN_STRATEGY="truncate_from_right"

# POWERLEVEL9K Color customizing
# Vi-Mode
POWERLEVEL9K_VI_INSERT_MODE_STRING='I'
POWERLEVEL9K_VI_COMMAND_MODE_STRING='N'
POWERLEVEL9K_VI_MODE_INSERT_BACKGROUND='033'
POWERLEVEL9K_VI_MODE_INSERT_FOREGROUND='000'
POWERLEVEL9K_VI_MODE_NORMAL_BACKGROUND='082'
POWERLEVEL9K_VI_MODE_NORMAL_FOREGROUND='000'
# Dir
POWERLEVEL9K_DIR_DEFAULT_BACKGROUND='001'
POWERLEVEL9K_DIR_DEFAULT_FOREGROUND='236'
POWERLEVEL9K_DIR_HOME_BACKGROUND='002'
POWERLEVEL9K_DIR_HOME_FOREGROUND='236'
POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND='014'
POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND='236'
# `git hub colors`
POWERLEVEL9K_VCS_CLEAN_BACKGROUND='002'
POWERLEVEL9K_VCS_CLEAN_FOREGROUND='236'
POWERLEVEL9K_VCS_MODIFIED_BACKGROUND='226'
POWERLEVEL9K_VCS_MODIFIED_FOREGROUND='236'
POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND='196'
POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND='236'
