live_config_reload = true

import = [
    # - "~/.config/alacritty/dracula.yml"
    "~/.config/alacritty/github_dark_high_contrast.toml"
]

[window]
opacity = 0.95
padding = { y = 0, x = 0 }
dynamic_padding = true
decorations = "Buttonless"
startup_mode = "Maximized" # Options: Maximized | SimpleFullscreen | Windowed | Fullscreen

[font]
normal.family = "JetBrainsMono Nerd Font"
size = 12.5

[[keyboard.bindings]]
key = "Return"
mods = "Command"
action = "ToggleSimpleFullscreen"

[[keyboard.bindings]]
key = "Left"
mods = "Alt"
chars = "\\x1bb"  # Skip word left

[[keyboard.bindings]]
key = "Right"
mods = "Alt"
chars = "\\x1bf"  # Skip word right

[[keyboard.bindings]]
key = "Left"
mods = "Command"
chars = "\\x1bOH"
mode = "AppCursor"  # Home

[[keyboard.bindings]]
key = "Right"
mods = "Command"
chars = "\\x1bOF"
mode = "AppCursor"  # End

[[keyboard.bindings]]
key = "Back"
mods = "Command"
chars = "\\x15"  # Delete line

[[keyboard.bindings]]
key = "Back"
mods = "Alt"
chars = "\\x1b\\x7f"  # Delete word
