live_config_reload = true

import = [
  # "~/.config/alacritty/dracula.yml",
  "~/.config/alacritty/github_dark_high_contrast.toml"
]

[window]
opacity = 0.95
padding = { y = 0, x = 0 }
dynamic_padding = true
decorations = "Buttonless"
startup_mode = "Maximized" # Options: Maximized | SimpleFullscreen | Windowed | Fullscreen

[font]
normal.family = "JetBrainsMono Nerd Font"
size = 12.5

[keyboard]
bindings = [
  # Toggle fullscreen
{ key = "Return", mods = "Command", action = "ToggleSimpleFullscreen" },

  # Navigation - Move by word
{ key = "Left",  mods = "Alt", chars = "\u001BB" },  # Skip word left
{ key = "Right", mods = "Alt", chars = "\u001BF" },  # Skip word right

  # Home & End keys
{ key = "Left",  mods = "Command", chars = "\u001BOH", mode = "AppCursor" },  # Home
{ key = "Right", mods = "Command", chars = "\u001BOF", mode = "AppCursor" },  # End

  # Delete bindings
{ key = "Back", mods = "Command", chars = "\u0015" },      # Delete line
{ key = "Back", mods = "Alt", chars = "\u001B\u007F" }     # Delete word
]
